version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      # Optional: If you want to mount your local nginx.conf
      # Make sure to uncomment the COPY line for nginx.conf in your Dockerfile as well.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro