version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge